Validation rule to release containers
campforce/auto-parts-retail pull request #14
Opened 2022-08-22 11:11 UTC by Erbol-ay

2022-08-22 11:48 UTC, belekomurzakov requested changes

2022-08-22 11:48 UTC, belekomurzakov commented on force-app/main/default/classes/triggerhandlers/ContainerReleasedTriggerHandler.cls
> +public with sharing class ContainerReleasedTriggerHandler {
there is already containertriggerhandler already exist, put ur logic there.

2022-08-23 11:44 UTC, dastan888 requested changes

2022-08-23 11:44 UTC, dastan888 commented on force-app/main/default/classes/services/ContainerReleasedTriggerTest.cls
> +public class ContainerReleasedTriggerTest {
put this into existing ContainerServiceTest class

2022-08-23 21:58 UTC, merged